///
///  @Generated by Swifixture
///

import Foundation


extension CustomStruct {
    static func fixture() -> Self {
        .init()
    }
}


extension ModuleQualifiedTypesStruct {
    static func fixture(
        string: Swift.String = "string",
        array: Swift.Array<Int> = [],
        date: Foundation.Date = .init()
    ) -> Self {
        .init(
            string: string,
            array: array,
            date: date
        )
    }
}


extension MultipleBindingsStruct {
    static func fixture(
        int: Int = 0,
        string: String = "string",
        x: Double = 0.0,
        y: Double = 0.0,
        flag: Bool = false
    ) -> Self {
        .init(
            int: int,
            string: string,
            x: x,
            y: y,
            flag: flag
        )
    }
}


extension NamespaceClass.InClass {
    static func fixture(
        string: String = "string"
    ) -> Self {
        .init(
            string: string
        )
    }
}


extension NamespaceEnum.InEnum {
    static func fixture(
        string: String = "string"
    ) -> Self {
        .init(
            string: string
        )
    }
}


extension NamespaceEnum.InExtension {
    static func fixture(
        string: String = "string"
    ) -> Self {
        .init(
            string: string
        )
    }
}


extension OneLineStruct {
    static func fixture(
        int: Int = 0,
        closure: @escaping (Int) -> Void = { _ in }
    ) -> Self {
        .init(
            int: int,
            closure: closure
        )
    }
}


extension VariousPropertiesStruct {
    static func fixture(
        any: Any = 0,
        anyObject: AnyObject = 0 as AnyObject,
        bool: Bool = false,
        character: Character = "c",
        data: Data = .init(),
        date: Date = .init(),
        double: Double = 0.0,
        float: Float = 0.0,
        int: Int = 0,
        int8: Int8 = 0,
        int16: Int16 = 0,
        int32: Int32 = 0,
        int64: Int64 = 0,
        set: Set<String> = [],
        string: String = "string",
        uint: UInt = 0,
        uint8: UInt8 = 0,
        uint16: UInt16 = 0,
        uint32: UInt32 = 0,
        uint64: UInt64 = 0,
        url: URL = .init(string: "http://localhost")!,
        uuid: UUID = .init(),
        optional: String? = nil,
        optionalGeneric: Optional<String> = nil,
        implicitlyUnwrappedOptional: String! = "implicitlyUnwrappedOptional",
        array: Array<String> = [],
        arrayLiteral: [String] = [],
        arrayOptional: [String]? = nil,
        dictionary: Dictionary<String, Any> = [:],
        dictionaryLiteral: [String: Any] = [:],
        dictionaryOptional: [String: Any]? = nil,
        tuple: (String, Int) = ("0", 0),
        tupleOptional: (String, Int)? = nil,
        tupleWithArgumentNames: (name: String, age: Int) = (name: "name", age: 0),
        tupleWithArgumentNamesOptional: (name: String, age: Int)? = nil,
        closure: @escaping () -> Void = { },
        closureOptional: (() -> Void)? = nil,
        closureWithArguments: @escaping (Int) -> String = { _ in "" },
        closureWithArgumentsOptional: ((Int) -> String)? = nil,
        sendableClosure: @Sendable @escaping () -> Void = { },
        customEnumWithOverride: CustomEnum = .a,
        customEnumWithOverride2: CustomEnum = .b,
        otherFixturableStruct: CustomStruct = .fixture()
    ) -> Self {
        .init(
            any: any,
            anyObject: anyObject,
            bool: bool,
            character: character,
            data: data,
            date: date,
            double: double,
            float: float,
            int: int,
            int8: int8,
            int16: int16,
            int32: int32,
            int64: int64,
            set: set,
            string: string,
            uint: uint,
            uint8: uint8,
            uint16: uint16,
            uint32: uint32,
            uint64: uint64,
            url: url,
            uuid: uuid,
            optional: optional,
            optionalGeneric: optionalGeneric,
            implicitlyUnwrappedOptional: implicitlyUnwrappedOptional,
            array: array,
            arrayLiteral: arrayLiteral,
            arrayOptional: arrayOptional,
            dictionary: dictionary,
            dictionaryLiteral: dictionaryLiteral,
            dictionaryOptional: dictionaryOptional,
            tuple: tuple,
            tupleOptional: tupleOptional,
            tupleWithArgumentNames: tupleWithArgumentNames,
            tupleWithArgumentNamesOptional: tupleWithArgumentNamesOptional,
            closure: closure,
            closureOptional: closureOptional,
            closureWithArguments: closureWithArguments,
            closureWithArgumentsOptional: closureWithArgumentsOptional,
            sendableClosure: sendableClosure,
            customEnumWithOverride: customEnumWithOverride,
            customEnumWithOverride2: customEnumWithOverride2,
            otherFixturableStruct: otherFixturableStruct
        )
    }
}


extension VariousPropertiesStruct.Nested {
    static func fixture(
        hoge: String = "hoge"
    ) -> Self {
        .init(
            hoge: hoge
        )
    }
}


extension VariousPropertiesStruct.Nested.Nested2 {
    static func fixture(
        fuga: String = "fuga"
    ) -> Self {
        .init(
            fuga: fuga
        )
    }
}
