import ArgumentParser
import Foundation
import Testing

@testable import Swifixture

final class SwifixtureTests {
    private let sourceFile = "Sample.swift"
    private let outputFile = "Fixtures.swift"
    
    init() async throws {
        try? FileManager.default.removeItem(at: URL(fileURLWithPath: sourceFile))
        try? FileManager.default.removeItem(at: URL(fileURLWithPath: outputFile))
    }
    
    deinit {
        try? FileManager.default.removeItem(at: URL(fileURLWithPath: sourceFile))
        try? FileManager.default.removeItem(at: URL(fileURLWithPath: outputFile))
    }
    
    @Test func run() async throws {
        let testDataURL = try #require(
            Bundle.module.url(forResource: "Resources/Source", withExtension: "swift")
        )
        let source = try String(contentsOf: testDataURL)
        try source.write(to: URL(fileURLWithPath: sourceFile), atomically: true, encoding: .utf8)

        try Swifixture
            .parse(["--source", sourceFile, "--output", outputFile])
            .run()

        let got = try String(contentsOf: URL(fileURLWithPath: outputFile))
        
        let expectedDataURL = try #require(
            Bundle.module.url(forResource: "Resources/Expected", withExtension: "swift")
        )
        let expected = try String(contentsOf: expectedDataURL)
        
        #expect(got == expected)
    }
    
    @Test func runWithCustomImportsAndTestableImports() async throws {
        try "".write(to: URL(fileURLWithPath: sourceFile), atomically: true, encoding: .utf8)
        
        try Swifixture
            .parse([
                "--source", sourceFile,
                "--output", outputFile,
                "--additional-imports", "Combine", "SwiftUI",
                "--testable-import", "Swifixture"
            ])
            .run()
        
        let got = try String(contentsOf: URL(fileURLWithPath: outputFile))
        
        let expected = """
            ///
            ///  @Generated by Swifixture
            ///

            import Foundation
            import Combine
            import SwiftUI

            @testable import Swifixture



            """
        
        #expect(got == expected)
    }
}
